model: ollama_chat/qwen2.5-coder:7b-instruct
no-gitignore: true
edit-format: udiff
map-refresh: files
map-multiplier-no-files: 0
map-tokens: 256
max-chat-history-tokens: 512
timeout: 60
stream: false
yes-always: true
