export FLASK_APP=hushline
export ADMIN_INPUT_SOURCE=environment
export ADMIN_SECRET=bi5FDwhZGKfc4urLJ_ChGtIAaOPgxd3RDOhnvct10mw=
export SQLALCHEMY_DATABASE_URI=sqlite:///hushline.db
export REGISTRATION_CODES_REQUIRED=False
export SESSION_COOKIE_NAME=session
