# vim: set syntax=dockerfile :
FROM python:3.12.6-slim-bookworm

# libffi-dev for Python C extensions
# libpq-dev for `psycopg` Python package
# curl for installing `cargo`
# clang, pkg-config, libpcsclite-dev, nettle-dev for `pysequoia`
RUN apt-get -o Acquire::Retries=10 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update && \
    apt-get -o Acquire::Retries=10 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 install -y --fix-missing --no-install-recommends \
    curl \
    build-essential \
    clang \
    pkg-config \
    libffi-dev \
    libpq-dev \
    libpcsclite-dev \
    nettle-dev \
    nodejs \
    npm && \
    rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN python -m pip install --no-cache-dir --upgrade "pip>=26,<27" && \
    python -m pip install --no-cache-dir poetry

RUN npm install --global prettier@3.3.3

WORKDIR /app

ENV PYTHONPATH=/app

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

ENV FLASK_APP="hushline"
CMD ["./scripts/dev_start.sh"]
