# vim: set syntax=dockerfile :
FROM python:3.12.6-slim-bookworm

# libffi-dev for Python C extensions
# libpq-dev for `psycopg` Python packge
# curl for installing `cargo`
# clang, pkg-config, libpscsclite-dev, nettle-dev for `pysequoia`
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        curl \
        build-essential \
        clang \
        pkg-config \
        libffi-dev \
        libpq-dev \
        libpcsclite-dev \
        nettle-dev \
        npm

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN pip install poetry

WORKDIR /app

COPY package.json package-lock.json .

RUN npm install

ENV PYTHONPATH=/app

COPY pyproject.toml poetry.lock .

RUN poetry install

ENV FLASK_APP="hushline"
CMD ["./scripts/dev_start.sh"]
