# vim: set syntax=dockerfile :
FROM python:3.12.6-slim-bookworm

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libffi-dev \
        libpq-dev

RUN pip install poetry

WORKDIR /app
ENV PYTHONPATH=/app

COPY pyproject.toml poetry.lock .

RUN poetry install
