import secrets
from typing import TYPE_CHECKING

from sqlalchemy.orm import Mapped, mapped_column, relationship

from hushline.config import EncryptedFieldWriteFormat
from hushline.crypto import (
    DICEWARE_WORDS,
    ENCRYPTED_FIELD_CONTRACT_BY_ID,
    decrypt_field,
    encrypt_field,
    encrypt_message,
    encrypted_field_write_format,
    is_encrypted_field_aead_envelope,
)
from hushline.db import db

if TYPE_CHECKING:
    from flask_sqlalchemy.model import Model

    from hushline.model import FieldDefinition, Message
else:
    Model = db.Model


def add_padding(value: str, block_size: int = 512) -> str:
    """
    To hide what field is being encrypted, we need to pad the value to a (roughly) fixed block size.
    This class is used to create a padded version of the field by random words at the end until it
    reaches a multiple of 512-character blocks.
    """
    value += "\n\n(Random text generated by Hush Line: lorum ipsum "

    # Add padding words
    target_len = block_size - (len(value) % block_size)
    padding = ""
    while len(padding) < target_len:
        padding += secrets.choice(DICEWARE_WORDS) + " "
    padding += ")"

    # Return the padded value
    return value + padding


class FieldValue(Model):
    __tablename__ = "field_values"

    id: Mapped[int] = mapped_column(primary_key=True, nullable=False, autoincrement=True)
    field_definition_id: Mapped[int] = mapped_column(
        db.ForeignKey("field_definitions.id"), nullable=True
    )
    field_definition: Mapped["FieldDefinition"] = relationship(uselist=False)
    message_id: Mapped[int] = mapped_column(
        db.ForeignKey("messages.id", ondelete="CASCADE"), nullable=True
    )
    message: Mapped["Message"] = relationship("Message", back_populates="field_values")
    _value: Mapped[str] = mapped_column(db.Text, nullable=False)
    encrypted: Mapped[bool] = mapped_column(nullable=True)

    def __init__(
        self,
        field_definition: "FieldDefinition",
        message: "Message",
        value: str,
        encrypted: bool,
    ) -> None:
        self.field_definition = field_definition
        self.message = message
        self.encrypted = encrypted
        if encrypted_field_write_format() == EncryptedFieldWriteFormat.ENVELOPE_AES_GCM:
            self._value = ""
            db.session.add(self)
            db.session.flush()
        # set the value AFTER setting the encrypted flag
        self.value = value

    def _encrypted_field_aad_values(self) -> dict[str, int]:
        if (
            self.id is None
            and encrypted_field_write_format() == EncryptedFieldWriteFormat.ENVELOPE_AES_GCM
        ):
            self._value = self._value or ""
            db.session.add(self)
            db.session.flush()
        if self.id is None or self.field_definition_id is None or self.message_id is None:
            raise ValueError("Field value encrypted-field AAD requires persisted row ids")
        return {
            "field_definition_id": self.field_definition_id,
            "field_value_id": self.id,
            "message_id": self.message_id,
        }

    def _encrypt_encrypted_field(self, value: str | None) -> str | None:
        if encrypted_field_write_format() != EncryptedFieldWriteFormat.ENVELOPE_AES_GCM:
            return encrypt_field(value)

        contract = ENCRYPTED_FIELD_CONTRACT_BY_ID["FieldValue.value"]
        return encrypt_field(
            value,
            contract=contract,
            aad_values=self._encrypted_field_aad_values(),
        )

    def _decrypt_encrypted_field(self, value: str | None) -> str | None:
        if value is None:
            return None
        if not is_encrypted_field_aead_envelope(value):
            return decrypt_field(value)

        contract = ENCRYPTED_FIELD_CONTRACT_BY_ID["FieldValue.value"]
        return decrypt_field(
            value,
            contract=contract,
            aad_values=self._encrypted_field_aad_values(),
        )

    @property
    def value(self) -> str | None:
        """
        This value is either a string with the actual value, PGP-encrypted data. If it's
        PGP-encrypted, the plaintext is padded with spaces at the end.
        """
        return self._decrypt_encrypted_field(self._value)

    @value.setter
    def value(self, value: str | list[str]) -> None:
        # Is value is a list, join it into a single string separated by newlines
        if isinstance(value, list):
            value = "\n".join(value)

        if self.encrypted and not value.startswith("-----BEGIN PGP MESSAGE-----"):
            # Encrypt with PGP

            # Pad the value to hide the length of the plaintext
            padded_value = add_padding(value)

            # Encrypt the padded value
            with db.session.no_autoflush:
                encryption_target = self.message.username.user.message_encryption_target
            if not encryption_target:
                raise ValueError("User does not have a PGP key")
            val_to_save = encrypt_message(padded_value, encryption_target)
        else:
            # Do not encrypt with PGP, and instead only encrypt with db key
            val_to_save = value

        # Encrypt the field
        val = self._encrypt_encrypted_field(val_to_save)
        if val is not None:
            self._value = val
        else:
            self._value = ""

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} {self.field_definition.label}>"
