name: Bug Report
description: Report a reproducible bug with clear expected versus actual behavior
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide a minimal, reproducible report.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the bug in 1-3 sentences.
      placeholder: Briefly describe the bug.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Choose the impact level.
      options:
        - critical (security, data loss, outage)
        - high (major workflow blocked)
        - medium (degraded behavior, workaround exists)
        - low (minor defect or cosmetic issue)
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - local
        - staging
        - production
        - single-tenant instance
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Provide exact steps.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / Commit (if known)
      placeholder: v0.5.66 or commit SHA
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Logs, screenshots, tracebacks, links.
      placeholder: Paste relevant evidence.
  - type: textarea
    id: fix_validation
    attributes:
      label: Fix Validation
      description: How should we verify this is fixed?
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues before opening this report.
          required: true
        - label: I have removed secrets and sensitive data from this issue.
          required: true
