"""empty message

Revision ID: 2e5a6b20908d
Revises: cab44a7264a5
Create Date: 2024-05-24 19:57:36.878591

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e5a6b20908d"
down_revision = "cab44a7264a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(sa.Column("contact_method", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_column("contact_method")

    # ### end Alembic commands ###
