"""add timecode to AuthenticationLog

Revision ID: 568f77aefcb4
Revises: ff59dfd3bdf6
Create Date: 2024-06-25 20:44:02.614282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568f77aefcb4'
down_revision = 'ff59dfd3bdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('authentication_logs', sa.Column('timecode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('secondary_usernames')
    op.drop_table('authentication_logs')
    op.drop_table('users')
    op.drop_table('invite_code')
    # ### end Alembic commands ###
