"""add verified fields

Revision ID: 83a6b3b09eca
Revises: 166a3402c391
Create Date: 2024-08-28 11:14:27.902082

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83a6b3b09eca"
down_revision = "166a3402c391"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extra_field_verified1", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("extra_field_verified2", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("extra_field_verified3", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("extra_field_verified4", sa.Boolean(), nullable=True))
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=512), nullable=False)
        batch_op.alter_column("is_verified", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("is_admin", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("show_in_directory", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("show_in_directory", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_admin", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_verified", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=512), nullable=True)
        batch_op.drop_column("extra_field_verified4")
        batch_op.drop_column("extra_field_verified3")
        batch_op.drop_column("extra_field_verified2")
        batch_op.drop_column("extra_field_verified1")

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table("authentication_logs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_authentication_logs_user_id_timestamp_successful",
            ["user_id", "timestamp", "successful"],
            unique=False,
        )

    # ### end Alembic commands ###
