"""empty message

Revision ID: cab44a7264a5
Revises: 9803e4dcb0a6
Create Date: 2024-05-24 19:55:09.067118

"""

# revision identifiers, used by Alembic.
revision = "cab44a7264a5"
down_revision = "9803e4dcb0a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
