name: hushline-agent
on:
  issues:
    types: [labeled]

jobs:
  run:
    if: contains(github.event.label.name, 'agent')
    runs-on: [self-hosted, agent]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry (user) + pin Python 3.11
        run: |
          python3.11 -m pip install --user --upgrade pip poetry
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Force Poetry venv in-project (.venv) with Python 3.11
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry env use /usr/bin/python3.11
          poetry run python -V
          echo "VENV=$(poetry env info -p)" >> "$GITHUB_ENV"
          echo "$VENV/bin" >> "$GITHUB_PATH"

      - name: Install project deps into the venv
        run: |
          poetry install -n
          poetry run pip install -U pytest aider-chat

      - name: Configure Git identity
        run: |
          git config user.name "hushline-agent"
          git config user.email "agent@users.noreply.github.com"

      - name: Ensure agent script is executable
        run: chmod +x ops/agent.sh

      - name: Run agent
        env:
          GH_TOKEN: ${{ secrets.AGENT_TOKEN }}
          PYTHON: ${{ env.VENV }}/bin/python
        run: ./ops/agent.sh "${{ github.event.issue.number }}"
