name: hushline-agent
on:
  issues:
    types: [labeled]

jobs:
  run:
    if: contains(github.event.label.name, 'agent')
    runs-on: [self-hosted, agent]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Python 3.11 user env
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          python3.11 -m pip --version
          pip3.11 --version

      - name: Install project deps with Poetry (3.11)
        run: |
          poetry env use "$(which python3.11)"
          poetry config virtualenvs.create false
          poetry install -n

      - name: Configure Git identity
        run: |
          git config user.name "hushline-agent"
          git config user.email "agent@users.noreply.github.com"

      - name: Ensure agent script is executable
        run: chmod +x ops/agent.sh

      - name: Run agent
        env:
          GH_TOKEN: ${{ secrets.AGENT_TOKEN }}
        run: ./ops/agent.sh "${{ github.event.issue.number }}"
