---
name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pip install poetry

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
            ${{ runner.os }}-poetry-
          path: |
            ~/.cache/pypoetry

      - name: Install Python dependencies
        run: poetry install --all-extras

      - name: Lint
        run: poetry -v run make lint

      - name: Test
        run: poetry -v run make test
        continue-on-error: true
